<?php

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-06-16 at 14:20:06.
 */
class KspliceTest extends TestCase
{
    /**
     * @var Ksplice
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Ksplice;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Detain\MyAdminKsplice\Ksplice::request
     * @todo   Implement testRequest().
     */
    public function testRequest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminKsplice\Ksplice::list_machines
     * @todo   Implement testList_machines().
     */
    public function testList_machines()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminKsplice\Ksplice::describe_machine
     * @todo   Implement testDescribe_machine().
     */
    public function testDescribe_machine()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminKsplice\Ksplice::ip_to_uuid
     * @todo   Implement testIp_to_uuid().
     */
    public function testIp_to_uuid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminKsplice\Ksplice::authorize_machine
     * @todo   Implement testAuthorize_machine().
     */
    public function testAuthorize_machine()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminKsplice\Ksplice::deauthorize_machine
     * @todo   Implement testDeauthorize_machine().
     */
    public function testDeauthorize_machine()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminKsplice\Ksplice::change_group
     * @todo   Implement testChange_group().
     */
    public function testChange_group()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
